name: The Upper Room Wellness
favicon: null
layout_spectrum: 0.6559179346077144
typography_spectrum: 0.6985342076513916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4600321815814823
  lightness: 0.1762735857628286
  saturation: 0.10141987074166536
  rhythmicContrast: 0.11248669470660388
purpose: []
